### PR TITLE
Add resolution for javascript verticles running on node.js

### PR DESCRIPTION
**Pull request by mellster2012**
Defensive implementation of node.js capabilities which only attempts resolution of javascript verticles using node.js if 'vertx.enableNodeJSVerticles' system property is explicitly set. Since the additional dependencies are needed to compile and test they have compile scope, but are not included in the jar, i.e. they have to be provided by a ready-made vertx-distro or added by the user. The dependencies are:
io.apigee.trireme:trireme-core, io.apigee.trireme:trireme-kernel, io.apigee.trireme:trireme-node10src, io.apigee.trireme:trireme-node12src, io.apigee.trireme:trireme-crypto, io.apigee.trireme:trireme-util ( all v0.8.6), commons-io:commons-io (v2.4) and org.mozilla:rhino (v1.7.7).

### CODE REVIEW

**Comment by michel-kraemer** [comment]
Interesting PR. Just out of curiosity, I wonder why you need all this code directly in vertx-lang-js. Isn't there a more non-intrusive way? I'm particularly worried about the additional dependencies that your PR adds, especially Mozilla Rhino.

Cheers,
Michel

**Comment by michel-kraemer** [comment]
With 'non-intrusive' I mean overwriting the factory in your own library. I did this in verx-lang-typescript and it works quite well there.

Michel

**Comment by mellster2012** [comment]
Hi Michel,

I have a less intrusive version at https://github.com/mellster2012/vertx-nodejs-service-factory
There are advantages to both ways (feels more natural to handle everything js in one module and not having two competing factories in the case a node.js verticle gets resolved via http-service-factory which is likely the main route for distributing node.js modules). In the vertx distro we use rhino is already included, just an earlier version. Once the team at apigee releases their successor rowboat based on Nashorn integration should become much simpler. Of course we can keep it as a module instead.
cheers

--Marco

**Comment by michel-kraemer** [comment]
Thanks, I understand the advantages. I was just curious but I'm not the one to decide whether this PR should be merged. I'm just saying I would be very careful with mixing different things here. I think this PR might introduce some coupling that *may* - on the long term - lead to bad code maintainability.

What do the others think? @vietj @purplefox ?

**Comment by vietj** [comment]
agreed with @michel-kraemer I believe it should go in a lang that builds on top of vertx-lang-js.

@mellster2012 can you explain the prb with http-service-verticle factory ?

**Comment by mellster2012** [comment]
@vietj No problem, I can make a separate module building on lang-js. The issue with http-service-factory is that it resolves nicely any zipped modules as long as you provide a service descriptor, which in case of a zipped node.js module would be package.json. From here it resolves the main "class" which is a javascript file, so it get's delegated from http-service-factory to JSVerticleFactory for final resolution. The JSVerticleFactory by itself does not know how to handle js scripts running on node, so it will fail. So there has to be a NodeJSVerticleFactory that registers on the js prefix, in my stand-alone module I gave it the order of -1 to get called before JSVerticleFactory and fall through and let JSVerticleFactory handle it if no node engine property or node_modules directory was found inside the module. In the integrated case we could let JSVerticleFactory handle both cases, simple js and node.js module. It's not really a big issue though.

**Comment by mellster2012** [comment]
I will move this into it's own module, vertx-lang-nodejs, while still extending from JsVerticleFactory and trying to reuse code where possible. I'll close this pull request and publish the new stand-alone module when ready.

**Comment by mellster2012** [comment]
All recent changes and refactoring have been merged into its own module (the toggling system property has been removed) and the description has been updated:
https://github.com/mellster2012/vertx-nodejs-service-factory

**Pull request closed without merging**
