### PR TITLE
Convert java.lang.Long to double is not a number since 1.8.0_92

### PR DESCRIPTION
**Pull request by vietj**
@pmlopes please review

### CODE REVIEW

**Comment by pmlopes** [comment]
This one is tricky, the tests are very simple however if you go to the max integer number (`Math.pow(2, 52) + 1`) from JS it fails:

```
java.lang.AssertionError: 
Expected :4.503599627370497E15
Actual   :1.0E10
```

**Comment by pmlopes** [comment]
Also the formatting is wrong, if should not be a floating point number, if you debug with nashorn print function you get it correct:

```
4503599627370497
```

**Comment by vietj** [comment]
yes I know... do we have another way to convert a Long to a JS number without loss of precision ?

**Comment by vietj** [comment]
we need to investigate this

**Comment by vietj** [comment]
the question is can nashorn represent this value at all?

**Comment by vietj** [comment]
yes it can

**Comment by vietj** [comment]
jjs> Math.pow(2, 52) + 1
4503599627370497
jjs> a = Math.pow(2, 52) + 1
4503599627370497
jjs> a.getClass()
class java.lang.Double

**Comment by pmlopes** [comment]
maybe we could do a `if (longValue < Math.pow(2, 53)) { return (int) longValue; } else { /* kaboom as expected in JS world! */ }`

**Comment by vietj** [comment]
can we try to use String as intermediary if the Long value is above a certain treshold ?

**Comment by pmlopes** [comment]
dah! crap we cannot downcast to int, 53 bit it higher than int32 :P

**Comment by vietj** [comment]
I think we can try this : add 0

```
jjs> a = Packages.java.lang.Long.parseLong("4503599627370497")
4503599627370497
jjs> a.getClass()
class java.lang.Long
jjs> b = a + 0
4503599627370497
jjs> b.getClass()
class java.lang.Double
```

**Comment by vietj** [comment]
what's the real problem actually ?

**Comment by vietj** [comment]
how did you reproduce the "java.lang.AssertionError" ?

**Comment by vietj** [comment]
@pmlopes not sure to understand how to reproducer what you see:

```
jjs> var a = (Math.pow(2, 52) + 1)
jjs> a 
4503599627370497
jjs> a.getClass()
class java.lang.Double
```

**Comment by pmlopes** [comment]
The big number issue is not really valid since it would be an abuse of JS Number which is not allowed to be over 53bits anyway. The fix is good and we can consider it closed.

**Pull request merged**
