### PR TITLE
Rewrite vertx-lang-js generator without MVEL

### PR DESCRIPTION
**Pull request by okou19900722**
https://github.com/vert-x3/issues/issues/367

### CODE REVIEW

**Comment by pmlopes** [comment]
I think we should copy so we can decouple the 2 modules

**Comment by pmlopes** [comment]
Only the common is referenced from the sockjs proxies

**Comment by okou19900722** [comment]
I think we can rewrite sockjs proxies

**Comment by okou19900722** [comment]
https://github.com/okou19900722/vertx-sockjs-service-proxy/tree/rewrite

**Pull request merged**
